import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Featured from '@/components/Featured/featured.js'
import TrustedBy from '@/components/TrustedBy/trustedBy.js'
import Slide from '@/components/Slide/slide.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>RetroCraft Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Featured />
        <TrustedBy />
        <Slide />
        <div className={styles.features}>
          <div className={styles.container}>
            <div className={styles.item1}>
              <h1 className={styles.h1}>A whole world of freelance talent available at your fingertips</h1>
              <div className={styles.title}>
                <img className={styles.img} src="/check.jpg" alt="" />
                The best for every budget
              </div>
              <p className={styles.p}>
                Find the right service for every price point. No hourly rates, just project-based pricing.
              </p>
              <div className={styles.title}>
                <img className={styles.img} src="/check.jpg" alt="" />
                Get quality work done quickly
              </div>
              <p className={styles.p}>
                Find a talented freelancer for your project in minutes, get long-lasting results.
              </p>
              <div className={styles.title}>
                <img className={styles.img} src="/check.jpg" alt="" />
                Pay when you're happy
              </div>
              <p className={styles.p}>
                Upfront quotes mean no surprises. Payments only get released when you approve.
              </p>
              <div className={styles.title}>
                <img className={styles.img} src="/check.jpg" alt="" />
                Count on 24/7 support
              </div>
              <p className={styles.p}>
                Our round-the-clock support team is available to help anytime, anywhere.
              </p>
            </div>
            <div>
              <img src="photog.jpg" alt="" width={500} />
            </div>
          </div>
        </div>
        <div className={styles.dfeatures}>
          <div className={styles.dcontainer}>
            <div className={styles.ditem1}>
              <h1 className={styles.h1}>RetroCraft business</h1>
              <h1 className={styles.h1}>A business solution designed for <i>teams</i></h1>
              <p className={styles.dp}>Upgrade to a curated experience packed with tools and benefits, dedicated to businesses</p>
              <div className={styles.dtitle}>
                <img className={styles.img} src="/check.jpg" alt="" />
                Connect to freelancers with proven business experience
              </div>
              <div className={styles.dtitle}>
                <img className={styles.img} src="/check.jpg" alt="" />
                Get matched with the perfect talent by a customer success manager
              </div>
              <div className={styles.dtitle}>
                <img className={styles.img} src="/check.jpg" alt="" />
                Manage your freelance workforce and onboard additional talent with an end-to-end SaaS solution
              </div>
              <button className={styles.btn}>Explore RetroCraft business</button>
            </div>
            <div>
              <img src="https://images.unsplash.com/photo-1486693128850-a77436e7ba3c?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="" width={500} />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
